units:
  kx: cx
  ky: cy
  px: kx + 4
  py: ky + 4
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [70, -180]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
          key.column_net: P020
        pinky:
          key.column_net: P022
        ring:
          key.stagger: 3
          key.column_net: P024
        middle:
          key.stagger: 2
          key.column_net: P100
        index:
          rows.mod.skip: true
          key.stagger: -2
          key.column_net: P011
        inner:
          key.stagger: -2
          rows.mod.skip: true
          key.column_net: P104
      rows:
        mod:
          row_net: P111
        bottom:
          row_net: P010
        home:
          row_net: P009
        top:
          row_net: P113
        num:
          row_net: P115
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_inner_bottom
        shift: [0.9kx, -1.2ky]
      columns:
        space:
          rows.cluster.splay: -30
          key.column_net: P104
        backspace:
          key.column_net: P106
      rows:
        cluster:
          row_net: P111
    layer2:
      key:
        padding: 1ky
        spread: 1kx
        column_net: P011
        row_net: P111
      anchor: 
        ref: matrix_inner_mod
        shift: [-0.3kx, 0]
    utils:
      key:
        padding: 1.5ky
        height: 1.5ky
      anchor:
        ref: matrix_inner_bottom
        shift: [1kx, 0.3ky]
      columns:
        single:
          key.column_net: P106
      rows:
        lower:
          row_net: P010
        upper:
          row_net: P113
  mirror: &mirror
    ref: thumbs_backspace_cluster
    distance: 2.5kx
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  boardleft:
    - what: polygon
      operation: stack
      fillet: 4
      points:
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_index_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: utils_single_upper
          shift: [0.5px, 0.75py]
        - ref: utils_single_lower
          shift: [0.5px, -0.75py]
        - ref: thumbs_backspace_cluster
          shift: [0.5px, 0.5py]
        - ref: thumbs_backspace_cluster
          shift: [0.5px, -0.5py]
        - ref: layer2
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_mod
          shift: [0.5px, -0.5py]
        - ref: matrix_outer_mod
          shift: [-0.5px, -0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]
  comboleft:
    - name: boardleft
    - operation: subtract
      name: keys
  boardright:
    - what: polygon
      operation: stack
      fillet: 4
      points:
        - ref: mirror_matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_index_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: mirror_utils_single_upper
          shift: [0.5px, 0.75py]
        - ref: mirror_utils_single_lower
          shift: [0.5px, -0.75py]
        - ref: mirror_thumbs_backspace_cluster
          shift: [0.5px, 0.5py]
        - ref: mirror_thumbs_backspace_cluster
          shift: [0.5px, -0.5py]
        - ref: mirror_layer2
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_pinky_mod
          shift: [0.5px, -0.5py]
        - ref: mirror_matrix_outer_mod
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5px, -0.5py]
  comboright:
  - name: boardright
  - operation: subtract
    name: keys
  fullcombo:
  - name: comboleft
  - operation: add
    name: comboright
pcbs:
  left:
    outlines:
      main:
        outline: boardleft
    footprints:
      choc_hotswap:
        where: /^matrix_.*|^thumbs.*|^layer2.*|^utils.*/
        what: choc
        params:
          hotswap: true
          reverse: false
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^matrix_(?!(?:inner_top|inner_num)).*|^thumbs.*|^layer2.*|^utils.*lower$/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8, -2]
          rotate: 90
      diode_controller_fix_1:
        what: diode
        where: /^utils_single_upper$/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -6]
      diode_controller_fix_2:
        what: diode
        where: /^matrix_(?:inner_top|inner_num).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -4]
      nice_nano:
        what: nice_nano
        params:
          orientation: "up"
        where:
          ref: utils_single_upper
          shift: [-6.5, 4.5]
          rotate: 180
  right:
    outlines:
      main:
        outline: boardright
    footprints:
      choc_hotswap:
        where: /^mirror_.*/
        what: choc
        params:
          hotswap: true
          reverse: false
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror_matrix_(?!(?:inner_top|inner_num)).*|^mirror_thumbs.*|^mirror_layer2.*|^mirror_utils.*lower$/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-8, -2]
          rotate: -90
      diode_controller_fix_1:
        what: diode
        where: /^mirror_utils_single_upper$/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -6]
      diode_controller_fix_2:
        what: diode
        where: /^mirror_matrix_(?:inner_top|inner_num).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -4]
      nice_nano:
        what: nice_nano
        params:
          orientation: "up"
        where:
          ref: mirror_utils_single_upper
          shift: [-6.5, 4.5]
          rotate: 0

